### ISSUE TITLE
Pass -h to tmate-slave

### ISSUE THREAD

**Issue by pjstadig** [nicopace/tmate-docker#1]
I would like to be able to pass the '-h' option to tmate-slave. tmate can then use this when it generates it's session command so that instead of `ssh -p2222 x7A3LpNrIskF4RFanVcWTBCYH@b40258bb359a` it would be `ssh -p2222 x7A3LpNrIskF4RFanVcWTBCYH@b40258bb359a@foo.bar.com`, which is more convenient for copying and pasting.

**Comment by afirel** [comment]
See pull request https://github.com/nicopace/tmate-docker/pull/4, it adds the '-h' option via an environment variable.

**Comment by nicopace** [comment]
Solved in #4
